
import { Language } from './translations';

export interface Category {
    id: string;
    slug: string;
    name: Partial<Record<Language, string>>;
    icon?: string; // We can add icons later
}

// User provided list, converted to structured data
// Note: Using Russian-Latin transliteration as requested for slugs, 
// providing proper labels for Uz/Ru/En where possible (auto-filling basics)
export const CATEGORIES: Category[] = [
    { id: '1', slug: 'kartonnye-korobki', name: { uz: 'Karton Qutilar', ru: 'Картонные коробки', en: 'Cardboard Boxes', qr: 'Karton Qutilar', zh: '纸箱', tr: 'Karton Kutular', tg: 'Қуттиҳои Картонӣ', kk: 'Картон Қораптар', tk: 'Karton Gutular', fa: 'جعبه‌های مقوایی' } },
    { id: '2', slug: 'kurierskie-pakety', name: { uz: 'Kuryer Paketlari', ru: 'Курьерские пакеты', en: 'Courier Bags', qr: 'Kuryer Paketleri', zh: '快递袋', tr: 'Kurye Çantaları', tg: 'Халтаҳои Курер', kk: 'Курьер Сөмкелері', tk: 'Kurýer Haltalar', fa: 'کیف‌های پیک' } },
    { id: '3', slug: 'pakety-pochta-rossii', name: { uz: 'Rossiya Pochta Paketlari', ru: 'Пакеты Почта России', en: 'Russian Post Bags', qr: 'Rossiya Pochta Paketleri', zh: '俄罗斯邮政袋', tr: 'Rusya Posta Çantaları', tg: 'Халтаҳои Почтаи Русия', kk: 'Ресей Поштасының Пакеттері', tk: 'Russiýa Poçta Haltalary', fa: 'کیف‌های پست روسیه' } },
    { id: '4', slug: 'bopp-pakety', name: { uz: 'BOPP Paketlar', ru: 'БОПП пакеты', en: 'BOPP Bags', qr: 'BOPP Paketler', zh: 'BOPP袋', tr: 'BOPP Çantalar', tg: 'Халтаҳои BOPP', kk: 'BOPP Пакеттер', tk: 'BOPP Haltalar', fa: 'کیف‌های BOPP' } },
    { id: '5', slug: 'zip-lock-pakety', name: { uz: 'Zip-Lock Paketlar', ru: 'Пакеты ZIP-LOCK', en: 'Zip-Lock Bags', qr: 'Zip-Lock Paketler', zh: '自封袋', tr: 'Kilitli Torbalar', tg: 'Халтаҳои ZIP-LOCK', kk: 'Зиплок Пакеттер', tk: 'Zip-Lock Haltalar', fa: 'کیف‌های زیپ‌لاک' } },
    { id: '6', slug: 'pakety-pvd', name: { uz: 'PVD Paketlar (Marketpleys)', ru: 'Пакеты ПВД для маркетплейсов', en: 'LDPE Bags', qr: 'PVD Paketler', zh: '低密度聚乙烯袋', tr: 'LDPE Çantalar', tg: 'Халтаҳои ПВД', kk: 'ПВД Пакеттер', tk: 'PVD Haltalar', fa: 'کیف‌های LDPE' } },
    { id: '7', slug: 'pakety-slajdery', name: { uz: 'Slayder Paketlar', ru: 'Пакеты слайдеры', en: 'Slider Bags', qr: 'Slayder Paketler', zh: '滑块袋', tr: 'Sürgülü Çantalar', tg: 'Халтаҳои Слайдер', kk: 'Слайдер Пакеттер', tk: 'Slaýder Haltalar', fa: 'کیف‌های اسلایدر' } },
    { id: '8', slug: 'plenka-upakovochnaya', name: { uz: 'Qadoqlash Plyonkasi', ru: 'Пленка упаковочная', en: 'Packaging Film', qr: 'Qadaqlaw Plyonkası', zh: '包装膜', tr: 'Ambalaj Filmi', tg: 'Филми Бастабандӣ', kk: 'Орауыш Пленка', tk: 'Gaplama Plýonkasy', fa: 'فیلم بسته‌بندی' } },
    { id: '9', slug: 'zapajshiki', name: { uz: 'Paket Payvandlagichlar', ru: 'Запайщики пакетов', en: 'Bag Sealers', qr: 'Paket Jalǵaǵıshlar', zh: '封口机', tr: 'Torba Kapatıcılar', tg: 'Дӯзандаҳои Халта', kk: 'Пакет Тігушілер', tk: 'Halta Ýapyjylar', fa: 'دستگاه‌های بندانداز' } },
    { id: '10', slug: 'kraft-pakety', name: { uz: 'Kraft Paketlar', ru: 'Крафт пакеты', en: 'Kraft Bags', qr: 'Kraft Paketler', zh: '牛皮纸袋', tr: 'Kraft Çantalar', tg: 'Халтаҳои Крафт', kk: 'Крафт Пакеттер', tk: 'Kraft Haltalar', fa: 'کیف‌های کرافت' } },
    { id: '11', slug: 'doy-pack', name: { uz: 'Doy-Pak (Doy Pack)', ru: 'Пакеты Дой-Пак', en: 'Doy Bags', qr: 'Doy-Pak', zh: '自立袋', tr: 'Doypack', tg: 'Дой-Пак', kk: 'Дой-Пак Пакеттер', tk: 'Doy-Pak', fa: 'کیف‌های داي‌پک' } },
    { id: '12', slug: 'polietilenovye-pakety', name: { uz: 'Polietilen Paketlar', ru: 'Полиэтиленовые пакеты', en: 'Polyethylene Bags', qr: 'Polietilen Paketler', zh: '聚乙烯袋', tr: 'Polietilen Çantalar', tg: 'Халтаҳои Полиэтилен', kk: 'Полиэтилен Пакеттер', tk: 'Polietilen Haltalar', fa: 'کیف‌های پلی‌اتیلن' } },
    { id: '13', slug: 'vozdushno-puzyrkovaya-plenka', name: { uz: 'Pufakchali Plyonka', ru: 'Воздушно-пузырьковая плёнка', en: 'Bubble Wrap', qr: 'Pufakchalı Plyonka', zh: '气泡膜', tr: 'Balonlu Naylon', tg: 'Пленкаи Ҳавобандак', kk: 'Көпіршікті Пленка', tk: 'Balonly Plýonka', fa: 'پوشش حبابی' } },
    { id: '14', slug: 'vozdushnaya-lenta', name: { uz: 'Havo Yostig\'i Lentasi', ru: 'Воздушная упаковочная лента', en: 'Air Cushion Film', qr: 'Hawa Jastıǵı Lentası', zh: '气垫膜', tr: 'Hava Yastığı Filmi', tg: 'Лентаи Ҳавоӣ', kk: 'Ауа Жастықшалы Таспа', tk: 'Howa Ýassygyny Lentas', fa: 'فیلم بالش هوایی' } },
    { id: '15', slug: 'pakety-s-vozdushnoj-podushkoj', name: { uz: 'Havo Yostiqli Paketlar', ru: 'Пакеты с воздушной подушкой', en: 'Air Cushion Bags', qr: 'Hawa Jastıqlı Paketler', zh: '气柱袋', tr: 'Hava Yastıklı Çantalar', tg: 'Халтаҳо бо Болишти Ҳавоӣ', kk: 'Ауа Жастықшалы Пакеттер', tk: 'Howa Ýassykly Haltalar', fa: 'کیف‌های بالش هوایی' } },
    { id: '16', slug: 'upakovochnaya-bumaga', name: { uz: 'Qadoqlash Qog\'ozi', ru: 'Упаковочная бумага', en: 'Wrapping Paper', qr: 'Qadaqlaw Qaǵazı', zh: '包装纸', tr: 'Ambalaj Kağıdı', tg: 'Коғази Бастабандӣ', kk: 'Орауыш Қағаз', tk: 'Gaplama Kagyz', fa: 'کاغذ بسته‌بندی' } },
    { id: '17', slug: 'bumazhnye-konverty', name: { uz: 'Qog\'oz Konvertlar', ru: 'Бумажные конверты', en: 'Paper Envelopes', qr: 'Qaǵaz Konvertler', zh: '信封', tr: 'Kağıt Zarflar', tg: 'Зарфҳои Коғазӣ', kk: 'Қағаз Хаттамалар', tk: 'Kagyz Konwertler', fa: 'پاکت‌های کاغذی' } },
    { id: '18', slug: 'termoetiketki', name: { uz: 'Termoetiketkalar', ru: 'Самоклеящиеся термоэтикетки', en: 'Thermal Labels', qr: 'Termoetiketkalar', zh: '热敏标签', tr: 'Termal Etiketler', tg: 'Этикеткаҳои Термо', kk: 'Термо Жапсырмалар', tk: 'Termoetikеtkalar', fa: 'برچسب‌های حرارتی' } },
    { id: '19', slug: 'scotch-kleykaya-lenta', name: { uz: 'Skotch va Yelim Lenta', ru: 'Скотч и клейкая лента', en: 'Adhesive Tape', qr: 'Skotch hám Jelil Lenta', zh: '胶带', tr: 'Yapışkan Bant', tg: 'Скотч ва Лентаи Часпанда', kk: 'Скотч және Желімді Таспа', tk: 'Skotch we Ýelimli Lenta', fa: 'نوار چسب' } },
    { id: '20', slug: 'stretch-plenka', name: { uz: 'Streich-Plyonka', ru: 'Стрейч-плёнка', en: 'Stretch Film', qr: 'Stretch-Plyonka', zh: '拉伸膜', tr: 'Streç Film', tg: 'Пленкаи Стрейч', kk: 'Стрейч Пленка', tk: 'Stref Plýonka', fa: 'فیلم کشبافت' } },
    { id: '21', slug: 'napolniteli', name: { uz: 'To\'ldiruvchilar', ru: 'Наполнители', en: 'Fillers', qr: 'Toldırıwshılar', zh: '填充物', tr: 'Dolgu Malzemeleri', tg: 'Пуркунандаҳо', kk: 'Толтырғыштар', tk: 'Doldurmalar', fa: 'پرکننده‌ها' } },
    { id: '22', slug: 'tubusy-kartonnye', name: { uz: 'Karton Tubuslar', ru: 'Тубусы картонные', en: 'Cardboard Tubes', qr: 'Karton Tubuslar', zh: '纸筒', tr: 'Karton Tüpler', tg: 'Тубусҳои Картонӣ', kk: 'Картон Түтіктер', tk: 'Karton Turbalar', fa: 'لوله‌های مقوایی' } },
    { id: '23', slug: 'gofrokarton', name: { uz: 'Gofrokarton', ru: 'Гофрокартон', en: 'Corrugated Cardboard', qr: 'Gofrokarton', zh: '瓦楞纸板', tr: 'Oluklu Mukavva', tg: 'Картони Гофрӣ', kk: 'Гофрокартон', tk: 'Gofrokarton', fa: 'مقوای موج‌دار' } },
    { id: '24', slug: 'zashitnyj-profil', name: { uz: 'Himoya Profili', ru: 'Защитный профиль', en: 'Protective Profile', qr: 'Qorǵaw Profili', zh: '保护型材', tr: 'Koruyucu Profil', tg: 'Профили Муҳофизатӣ', kk: 'Қорғаныш Профилі', tk: 'Goranmak Profili', fa: 'پروفیل محافظ' } },
    { id: '25', slug: 'plastikovye-korobki', name: { uz: 'Plastik Qutilar', ru: 'Пластиковые коробки', en: 'Plastic Boxes', qr: 'Plastik Qutilar', zh: '塑料盒', tr: 'Plastik Kutular', tg: 'Қуттиҳои Пластикӣ', kk: 'Пластик Қораптар', tk: 'Plastik Gutular', fa: 'جعبه‌های پلاستیکی' } },
    { id: '26', slug: 'vspenennyj-pe', name: { uz: 'Ko\'pikli Polietilen', ru: 'Вспененный полиэтилен', en: 'PE Foam', qr: 'Kópikli Polietilen', zh: 'PE泡沫', tr: 'PE Köpük', tg: 'Кафки Полиэтилен', kk: 'Кебікті Полиэтилен', tk: 'Köpükli PE', fa: 'فوم پلی‌اتیلن' } },
    { id: '27', slug: 'pakety-iz-vspenennogo-pe', name: { uz: 'Ko\'pikli PE Paketlar', ru: 'Пакеты из вспененного ПЭ', en: 'PE Foam Bags', qr: 'Kópikli PE Paketler', zh: 'PE泡沫袋', tr: 'PE Köpük Torbalar', tg: 'Халтаҳои Кафки PE', kk: 'Кебікті PE Пакеттер', tk: 'Köpükli PE Haltalar', fa: 'کیف‌های فوم PE' } },
    { id: '28', slug: 'samokleyashiesya-karmany', name: { uz: 'Yelimli Cho\'ntaklar', ru: 'Самоклеящиеся карманы', en: 'Adhesive Pockets', qr: 'Jelilli Qaltalar', zh: '自粘袋', tr: 'Yapışkanlı Cepler', tg: 'Ҷайбҳои Часпанда', kk: 'Желімді Қалталар', tk: 'Ýelimli Jüpler', fa: 'جیب‌های چسبنده' } },
    { id: '29', slug: 'rashodniki-dlya-magazinov', name: { uz: 'Do\'konlar uchun mollar', ru: 'Расходники для магазинов', en: 'Retail Supplies', qr: 'Dukanlar ushın zatlar', zh: '零售用品', tr: 'Mağaza Malzemeleri', tg: 'Масрафоти Мағозаҳо', kk: 'Дүкен Тауарлары', tk: 'Dükanlara Sarp Edilýän', fa: 'ملزومات فروشگاه' } },
    { id: '30', slug: 'vakuumnye-pakety', name: { uz: 'Vakuum Paketlar', ru: 'Вакуумные пакеты', en: 'Vacuum Bags', qr: 'Vakuum Paketler', zh: '真空袋', tr: 'Vakum Poşetleri', tg: 'Халтаҳои Вакуумӣ', kk: 'Вакуумдық Пакеттер', tk: 'Wakuum Haltalar', fa: 'کیف‌های وکیوم' } },
    { id: '31', slug: 'termousadochnaya-plenka', name: { uz: 'Termo-qisqaruvchi Plyonka', ru: 'Термоусадочная пленка', en: 'Shrink Film', qr: 'Termo-qısqarıwshı Plyonka', zh: '收缩膜', tr: 'Shrink Film', tg: 'Пленкаи Термоиҷмоъ', kk: 'Термо Жиырылғыш Пленка', tk: 'Termokiçelýän Plýonka', fa: 'فیلم شرینک' } },
    { id: '32', slug: 'meshki-pp', name: { uz: 'PP Qoplar', ru: 'Мешки полипропиленовые', en: 'PP Bags (Woven)', qr: 'PP Qaplar', zh: 'PP编织袋', tr: 'PP Çuval', tg: 'Халтаҳои Полипропилен', kk: 'PP Қаптар', tk: 'PP Haltalar', fa: 'کیسه‌های PP' } },
    { id: '33', slug: 'lenta-pp', name: { uz: 'PP Lenta (Tasma)', ru: 'Полипропиленовая лента', en: 'PP Strap', qr: 'PP Lenta', zh: 'PP打包带', tr: 'PP Şerit', tg: 'Лентаи Полипропилен', kk: 'PP Таспа', tk: 'PP Lenta', fa: 'نوار PP' } },
    { id: '34', slug: 'termopakety', name: { uz: 'Termo Paketlar (Sumka)', ru: 'Термопакеты, термосумки', en: 'Thermal Bags', qr: 'Termo Paketler', zh: '保温袋', tr: 'Termal Çantalar', tg: 'Халтаҳои Термо', kk: 'Термо Пакеттер', tk: 'Termo Haltalar', fa: 'کیف‌های حرارتی' } },
    { id: '35', slug: 'shpagaty-shnury', name: { uz: 'Iplar va Arqonlar', ru: 'Шпагаты и шнуры', en: 'Twines and Cords', qr: 'Jıpler hám Arqanlar', zh: '绳索', tr: 'İpler ve Kordonlar', tg: 'Ресмонҳо ва Тордонҳо', kk: 'Жіптер мен Арқандар', tk: 'Ýüpler we Kordlar', fa: 'نخ‌ها و طناب‌ها' } },
    { id: '36', slug: 'plomby', name: { uz: 'Plombalar', ru: 'Пломбы', en: 'Security Seals', qr: 'Plombalar', zh: '安全封条', tr: 'Güvenlik Mühürleri', tg: 'Пломбаҳо', kk: 'Пломбалар', tk: 'Plombalar', fa: 'مهرهای امنیتی' } },
    { id: '37', slug: 'kanstovary', name: { uz: 'Kanselyariya', ru: 'Канцтовары', en: 'Stationery', qr: 'Kanselyariya', zh: '文具', tr: 'Kırtasiye', tg: 'Тавоноии Дафтарӣ', kk: 'Кеңсе Тауарлары', tk: 'Kanseleýar', fa: 'لوازم‌التحریر' } },
    { id: '38', slug: 'banki-pet', name: { uz: 'PET Bankalar', ru: 'Банки ПЭТ', en: 'PET Jars', qr: 'PET Bankalar', zh: 'PET罐', tr: 'PET Kavanozlar', tg: 'Банкаҳои PET', kk: 'PET Банкілер', tk: 'PET Bankalar', fa: 'شیشه‌های PET' } },
    { id: '39', slug: 'sredstva-zashity', name: { uz: 'Himoya Vositalari', ru: 'Одноразовые средства защиты', en: 'Disposable Protection', qr: 'Qorǵaw Quralları', zh: '一次性防护用品', tr: 'Tek Kullanımlık Koruma', tg: 'Воситаҳои Муҳофизати Якбора', kk: 'Бір Рет Қолданылатын Қорғаныш', tk: 'Bir Gezeklik Goranmak', fa: 'وسایل محافظتی یکبار مصرف' } },
    { id: '40', slug: 'pallety', name: { uz: 'Palletlar', ru: 'Паллеты / Поддоны', en: 'Pallets', qr: 'Palletlar', zh: '托盘', tr: 'Paletler', tg: 'Паллетҳо', kk: 'Паллеттер', tk: 'Palletler', fa: 'پالت‌ها' } }
];
