import jsPDF from 'jspdf';
import { BoxDimensions } from './types';
import { Language } from './translations';

// Constants for fonts
const FONT_URL = "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Regular.ttf";
const FONT_NAME = "Roboto-Regular";

export interface PDFGenOptions {
    fileName: string;
    title: string;
    dims: BoxDimensions;
    t: (key: string) => string;
    drawFn: (doc: jsPDF, startX: number, startY: number) => void;
    totalSize: { w: number, h: number };
}

export const generateUnformattedPDF = async (options: PDFGenOptions) => {
    // Fallback if font fails
    const doc = new jsPDF({
        orientation: 'landscape',
        unit: 'mm',
        format: [options.totalSize.w + 200, options.totalSize.h + 200]
    });

    // Attempt to load custom font for Cyrillic support
    try {
        const response = await fetch(FONT_URL);
        const buffer = await response.arrayBuffer();
        const fontFileName = "Roboto-Regular.ttf";

        // Add font to VFS
        doc.addFileToVFS(fontFileName, Buffer.from(buffer).toString('binary'));
        doc.addFont(fontFileName, "Roboto", "normal");
        doc.setFont("Roboto");
    } catch (e) {
        console.warn("Failed to load custom font, falling back to default.", e);
        // Default font (Helvetica) usually doesn't support Cyrillic/Uzbek special chars well
    }

    // Header
    doc.setFontSize(24);
    doc.text(options.title, 20, 20);

    // Metadata
    doc.setFontSize(10);
    doc.text(`Dimensions: ${options.dims.l}x${options.dims.w}x${options.dims.h} mm`, 20, 30);
    doc.text(`Generated by PACK24.UZ`, 20, 35);

    doc.setLineWidth(0.5);
    doc.setDrawColor(0, 0, 0);

    // Draw Content
    // Center it roughly? Or use start offsets
    // We expect drawFn to use relative coords or we pass a start offset
    // Let's pass a fixed reasonable start offset for now
    const startX = 150;
    const startY = 50 + options.dims.h; // Safe margin

    options.drawFn(doc, startX, startY);

    doc.save(options.fileName);
};
