// ─── AI Knowledge Base Articles ──────────────────────────────────────────────
import type { KnowledgeArticle } from './index';

export const KNOWLEDGE_BASE: KnowledgeArticle[] = [
    {
        id: 'price',
        keywords: {
            uz: ['narx', 'qancha', 'summa', 'pul', 'necha pul', 'hisob'],
            ru: ['цена', 'сколько', 'стоимость', 'деньги', 'почем', 'расчет'],
            en: ['price', 'cost', 'how much', 'money', 'calculate'],
            qr: ['baha', 'qansha', 'pul'],
            zh: ['价格', '多少钱', '成本'],
            tr: ['fiyat', 'kac para', 'ucret'],
            tg: ['нарх', 'қадар', 'пул', 'ҳисоб'],
            kk: ['баға', 'қанша', 'ақша', 'есеп'],
            tk: ['baha', 'näçe', 'pul', 'hasap'],
            fa: ['قیمت', 'چقدر', 'پول', 'هزینه'],
        },
        responses: {
            uz: "Siz tanlagan konfiguratsiya bo'yicha taxminiy jami narx: {{totalPrice}}. Bir dona uchun: {{unitPrice}}. Aniq hisob-kitob uchun buyurtma tugmasini bosishingiz mumkin.",
            ru: "Примерная общая стоимость: {{totalPrice}}. За штуку: {{unitPrice}}. Для точного расчета нажмите кнопку заказа.",
            en: "Estimated total price: {{totalPrice}}. Per unit: {{unitPrice}}.",
            qr: "Jami baha: {{totalPrice}}. Bir dana ushın: {{unitPrice}}.",
            zh: "预计总价: {{totalPrice}}. 单价: {{unitPrice}}.",
            tr: "Tahmini toplam fiyat: {{totalPrice}}. Birim fiyatı: {{unitPrice}}.",
            tg: "Нархи тахминии умумӣ: {{totalPrice}}. Барои 1 дона: {{unitPrice}}.",
            kk: "Шамалы жалпы баға: {{totalPrice}}. Бір данаға: {{unitPrice}}.",
            tk: "Takmynan jemi baha: {{totalPrice}}. Her sany üçin: {{unitPrice}}.",
            fa: "قیمت تخمینی کل: {{totalPrice}}. هر دانه: {{unitPrice}}.",
        }
    },
    {
        id: 'moq',
        keywords: {
            uz: ['kam', 'oz', 'minimum', 'moq', 'dona', 'zakaz', 'partiya'],
            ru: ['мало', 'минимум', 'минимальный', 'партия', 'тираж', 'moq'],
            en: ['moq', 'minimum', 'small batch', 'order quantity'],
            qr: ['az', 'minimum'],
            zh: ['最小', '批量'],
            tr: ['minimum', 'adet'],
            tg: ['кам', 'ҳадди ақал', 'минимум', 'партия'],
            kk: ['аз', 'минимум', 'партия'],
            tk: ['az', 'minimum', 'partiýa'],
            fa: ['کم', 'حداقل', 'سفارش کوچک'],
        },
        responses: {
            uz: "Bizda 'Minimal Buyurtma' (MOQ) yo'q! Boshqalar 2000+ talab qilganda, siz bizdan 72 dona yoki undan kam qutini ham buyurtma qilishingiz mumkin.",
            ru: "У нас нет минимального заказа (Zero MOQ)! В отличие от других заводов (2000+ шт), мы предлагаем партии от 72 шт.",
            en: "We offer Zero MOQ! Unlike traditional manufacturers requiring 2000+ units, you can order small batches (e.g., 72 units).",
            qr: "Bizde minimal buyırtpa sheklewi joq. 72 dana bolsada tayarlap beremiz.",
            zh: "我们零最小起订量！您可以订购小批量（例如72件）。",
            tr: "Minimum sipariş miktarımız yoktur! 72 adet gibi küçük partilerle sipariş verebilirsiniz.",
            tg: "Мо ҳадди ақали фармоиш надорем! Шумо метавонед аз 72 дона фармоиш диҳед.",
            kk: "Бізде минималды тапсырыс жоқ! 72 данадан бастап тапсырыс бере аласыз.",
            tk: "Bizde iň az sargyt ýok! 72 sany ýaly kiçi partiýa sargyt edip bilersiňiz.",
            fa: "ما حداقل سفارش نداریم! می‌توانید از ۷۲ عدد سفارش دهید.",
        }
    },
    {
        id: 'validation',
        keywords: {
            uz: ['startup', 'startap', 'sinov', 'yangilik', 'test', 'xavf', 'risk'],
            ru: ['стартап', 'тест', 'проверка', 'риск', 'валидация'],
            en: ['startup', 'validation', 'test', 'risk'],
            qr: ['startap', 'test'],
            zh: ['启动', '测试'],
            tr: ['girisim', 'test'],
            tg: ['стартап', 'санҷиш', 'хатар'],
            kk: ['стартап', 'тест', 'тәуекел'],
            tk: ['startap', 'synag', 'töwekgelçilik'],
            fa: ['استارتاپ', 'آزمایش', 'ریسک'],
        },
        responses: {
            uz: "Pack24 startaplar uchun ideal yechim. Kichik partiya bilan savdoni boshlang va bozorni sinovdan o'tkazing.",
            ru: "Pack24 AI идеально подходит для стартапов. Проведите валидацию рынка без риска с малой партией.",
            en: "Perfect for Market Validation. Mitigate risk by ordering small batches.",
            qr: "Startaplar ushın qolaylı. Bozardı tekseriw ushın kishi partiya menen baslań.",
            zh: "非常适合市场验证。通过小批量订购降低风险。",
            tr: "Pazar doğrulaması için mükemmel. Küçük partilerle risk almadan başlayın.",
            tg: "Барои стартапҳо идеалӣ. Бо партияи хурд бозорро санҷед.",
            kk: "Стартаптарға идеал. Кішігірім партиямен нарықты тексеріп алыңыз.",
            tk: "Başlangyç işler üçin amatly. Kiçi partiýa bilen bazary synap görüň.",
            fa: "برای استارتاپ‌ها عالی است. با سفارش کوچک بازار را آزمایش کنید.",
        }
    },
    {
        id: 'design_ai',
        keywords: {
            uz: ['dizayn', 'dizayner', 'logo', 'chizma', '3d', 'konstruktor'],
            ru: ['дизайн', 'дизайнер', 'лого', 'чертеж', '3d', 'конструктор'],
            en: ['design', 'designer', 'logo', 'drawing', '3d'],
            qr: ['dizayn', 'suwret'],
            zh: ['设计', '商标'],
            tr: ['tasarim', 'logo'],
            tg: ['дизайн', 'нақша', 'лого', '3d'],
            kk: ['дизайн', 'сурет', 'лого', '3d'],
            tk: ['dizaýn', 'logo', 'çyzgy', '3d'],
            fa: ['طراحی', 'لوگو', 'نقشه', '3d'],
        },
        responses: {
            uz: "Qimmat dizaynerlar shart emas! Pack24 AI texnologiyasi yordamida o'z qutingiz 3D modelini soniyalar ichida yarating.",
            ru: "Забудьте о дорогих дизайнерах! С AI технологией вы получите 3D модель за секунды.",
            en: "No need for expensive designers. Our AI generates dielines and 3D models instantly.",
            qr: "Dizaynerge pul shashpań. AI arqalı o'z qutińizdi jaratıń.",
            zh: "无需昂贵的设计师。我们的AI即时生成3D模型。",
            tr: "Pahalı tasarımcılara gerek yok. AI teknolojimizle saniyeler içinde tasarım yapın.",
            tg: "Дизайнерони гарон лозим нест! Бо AI технологияи мо модели 3D-ро дар сония созед.",
            kk: "Қымбат дизайнерлер қажет емес! AI технологиямызбен 3D моделін секундтарда жасаңыз.",
            tk: "Gymmat dizaýnerler gerek däl! AI tehnologiýamyz bilen 3D modeli sekuntda dörediň.",
            fa: "طراح گران نیاز نیست! با فناوری AI ما در ثانیه مدل سه‌بعدی بسازید.",
        }
    },
    {
        id: 'export_decree',
        keywords: {
            uz: ['eksport', 'export', 'chet el', 'rossiya', 'yevropa', 'pq', 'qaror', 'subsidiya'],
            ru: ['экспорт', 'за рубеж', 'россия', 'европа', 'пк', 'постановление', 'субсидия'],
            en: ['export', 'abroad', 'decree', 'subsidy', 'government'],
            qr: ['eksport', 'qarar'],
            zh: ['出口', '补贴'],
            tr: ['ihracat', 'tesvik'],
            tg: ['содирот', 'экспорт', 'қарор', 'субсидия'],
            kk: ['экспорт', 'шетелге', 'жарлық', 'субсидия'],
            tk: ['eksport', 'daşary ýurt', 'karar', 'subsidiýa'],
            fa: ['صادرات', 'خارج', 'حکم', 'یارانه'],
        },
        responses: {
            uz: "O'zbekiston eksportchilari uchun PQ-136 qaroriga asosan 2028-yilgacha imtiyozlardan foydalaning. Bizning qutilar xalqaro talablarga javob beradi.",
            ru: "Для экспортеров Узбекистана! Согласно ПК-136, действуют субсидии до 2028 года. Наши упаковки соответствуют международным стандартам.",
            en: "Attention Exporters! Under Decree PQ-136, Uzbekistan supports exporters until 2028. We provide compliant packaging.",
            qr: "Eksportshılar ushın PQ-136 qararı boyınsha jeńillikler bar.",
            zh: "出口商请注意！根据PQ-136法令，乌兹别克斯坦支持出口商。",
            tr: "İhracatçılar için PQ-136 kararnamesi kapsamında teşvikler mevcuttur.",
            tg: "Барои содиркунандагони Ӯзбекистон! Мувофиқи ПҚ-136, то соли 2028 имтиёзот мавҷуданд.",
            kk: "Өзбекстан экспорттаушылары үшін! ПҚ-136 бойынша 2028 жылға дейін жеңілдіктер бар.",
            tk: "Özbegistanyň eksportçylary üçin! PQ-136 karary boýunça 2028-nji ýyla çenli ýeňillikler bar.",
            fa: "برای صادرکنندگان ازبکستان! طبق PQ-136 تا ۲۰۲۸ مزایا وجود دارد.",
        }
    },
    {
        id: 'standards',
        keywords: {
            uz: ['standart', 'gap', 'global', 'gigiena', 'ekologiya', 'eco'],
            ru: ['стандарт', 'гап', 'глобал', 'гигиена', 'экология', 'эко'],
            en: ['standard', 'gap', 'hygiene', 'eco', 'sustainable'],
            qr: ['standart', 'taza'],
            zh: ['标准', '卫生'],
            tr: ['standart', 'hijyen'],
            tg: ['стандарт', 'экология', 'тозагӣ'],
            kk: ['стандарт', 'экология', 'тазалық'],
            tk: ['standart', 'ekologiýa', 'arassa'],
            fa: ['استاندارد', 'بهداشت', 'محیط زیست'],
        },
        responses: {
            uz: "GLOBAL G.A.P standartlari: Gigienik toza qadoq va QR-kod orqali mahsulot kuzatuvi. Biz ekologik toza kartonni tavsiya qilamiz.",
            ru: "Соответствие GLOBAL G.A.P: Гигиеничная упаковка и прослеживаемость через QR-коды. Экологичный картон.",
            en: "We focus on GLOBAL G.A.P compliance: Hygienic packaging, traceability via QR codes, and sustainable eco-friendly materials.",
            qr: "Xalıqaralıq standartlarǵa juwap beremiz. Ekologiyalıq taza ónim.",
            zh: "符合全球G.A.P标准。环保材料替代塑料。",
            tr: "GLOBAL G.A.P uyumluluğu sağlıyoruz. Çevre dostu malzemeler.",
            tg: "Мувофиқати GLOBAL G.A.P: Қуттиҳои тоза ва ЭКОЛОГӢ.",
            kk: "GLOBAL G.A.P стандарттарына сәйкестік: Таза орам және экологиялық материалдар.",
            tk: "GLOBAL G.A.P standartlaryna laýyklyk: Arassa gaplama we ekologiýa taýdan arassa materiallar.",
            fa: "مطابقت با GLOBAL G.A.P: بسته‌بندی بهداشتی و مواد دوستدار محیط زیست.",
        }
    },
    {
        id: 'product_catalog',
        keywords: {
            uz: ['katalog', 'tayyor', 'mahsulot', 'tur', 'assortiment'],
            ru: ['каталог', 'готовые', 'продукт', 'вид', 'ассортимент'],
            en: ['catalog', 'ready', 'product', 'range'],
            qr: ['katalog', 'tayın'],
            zh: ['目录', '现成'],
            tr: ['katalog', 'urun'],
            tg: ['каталог', 'маҳсулот', 'навъ'],
            kk: ['каталог', 'өнім', 'түр'],
            tk: ['katalog', 'taýyn', 'önüm'],
            fa: ['کاتالوگ', 'محصول', 'نوع'],
        },
        responses: {
            uz: "Bizning katalogimizda 200 ga yaqin tayyor mahsulotlar mavjud. Eng keng assortimentni taklif etamiz.",
            ru: "В каталоге около 200 готовых решений. Широчайший ассортимент.",
            en: "We have nearly 200 ready-to-use products in our catalog.",
            qr: "Bizde 200 den aslam tayın qutı túrleri bar.",
            zh: "我们拥有近200种现成产品目录。",
            tr: "200'e yakın hazır ürün çeşidimiz mevcuttur.",
            tg: "Дар каталоги мо қариб 200 маҳсулоти омода мавҷуд аст.",
            kk: "Біздің каталогта 200-ге жуық дайын өнімдер бар.",
            tk: "Biziň katalogymyzda 200-e golaý taýyn önüm bar.",
            fa: "در کاتالوگ ما نزدیک به ۲۰۰ محصول آماده وجود دارد.",
        }
    },
    {
        id: 'delivery',
        keywords: {
            uz: ['yetkazib', 'dostavka', 'olib borish', 'yuk', 'transport'],
            ru: ['доставка', 'привезти', 'транспорт', 'логистика', 'отправка'],
            en: ['delivery', 'shipping', 'transport', 'logistics'],
            qr: ['jetkiziw', 'dostavka'],
            zh: ['运输', '送货'],
            tr: ['nakliye', 'teslimat'],
            tg: ['таҳвил', 'тавзеъ', 'нақлиёт'],
            kk: ['жеткізу', 'тасымал', 'логистика'],
            tk: ['eltip bermek', 'daşamak', 'logistika'],
            fa: ['تحویل', 'ارسال', 'حمل‌ونقل'],
        },
        responses: {
            uz: "Toshkent shahri ichida yetkazib berish bepul (katta hajmdagi buyurtmalar uchun). Viloyat va eksport uchun logistika xizmatlarimiz mavjud.",
            ru: "Доставка по Ташкенту бесплатная (для оптовых заказов). Организуем логистику в области и на экспорт.",
            en: "Free delivery in Tashkent for bulk orders. We also handle regional and export logistics.",
            qr: "Tashkent qalası ishine jetkiziw biypul. Wálayatlarǵa kelisim tiykarında.",
            zh: "塔什干市内批量订单免费送货。提供区域物流。",
            tr: "Taşkent içi toplu siparişlerde teslimat ücretsizdir.",
            tg: "Таҳвил дар шаҳри Тошканд барои бузургпартия ройгон аст.",
            kk: "Ташкент қаласы бойынша жаппай тапсырыстарда жеткізу тегін.",
            tk: "Daşkentde uly sargytlar üçin eltip bermek mugt.",
            fa: "تحویل در تاشکند برای سفارش‌های عمده رایگان است.",
        }
    },
    {
        id: 'contact',
        keywords: {
            uz: ['bog\'lanish', 'telefon', 'raqam', 'manzil', 'aloqa', 'ofis'],
            ru: ['контакт', 'телефон', 'номер', 'адрес', 'связь', 'офис'],
            en: ['contact', 'phone', 'number', 'address', 'call', 'office'],
            qr: ['baylanıs', 'telefon', 'nomer'],
            zh: ['联系', '电话', '地址'],
            tr: ['iletisim', 'telefon', 'adres'],
            tg: ['тамос', 'телефон', 'суроға'],
            kk: ['байланыс', 'телефон', 'мекенжай'],
            tk: ['habarlaşmak', 'telefon', 'adres'],
            fa: ['تماس', 'تلفن', 'آدرس'],
        },
        responses: {
            uz: "Manzil: Toshkent sh., Chilonzor tumani. Tel: +998 90 123-45-67. Telegram: @pack24uz. Onlayn maslahatchi 24/7 aloqada.",
            ru: "Адрес: г. Ташкент, Чиланзар. Тел: +998 90 123-45-67. Telegram: @pack24uz. Консультант 24/7.",
            en: "Address: Tashkent, Chilanzar. Phone: +998 90 123-45-67. Telegram: @pack24uz. 24/7 Support.",
            qr: "Mánzil: Tashkent q., Chilanzar. Tel: +998 90 123-45-67.",
            zh: "地址：塔什干，奇兰扎尔区。电话：+998 90 123-45-67。",
            tr: "Adres: Taşkent, Chilanzar. Tel: +998 90 123-45-67.",
            tg: "Суроға: ш. Тошканд, ноҳияи Чилонзор. Тел: +998 90 123-45-67.",
            kk: "Мекенжай: Ташкент қ., Чиланзар. Тел: +998 90 123-45-67.",
            tk: "Adres: Daşkent ş., Çilanzar. Tel: +998 90 123-45-67.",
            fa: "آدرس: تاشکند، چیلونزور. تلفن: ۹۸۷-۶۵-۴۳۲۱ ۰۹ ۹۹۸+.",
        }
    },
    {
        id: 'material',
        keywords: {
            uz: ['material', 'qog\'oz', 'karton', 'qalinlik', 'gofra'],
            ru: ['материал', 'бумага', 'картон', 'толщина', 'гофра'],
            en: ['material', 'paper', 'cardboard', 'thickness', 'corrugated'],
            qr: ['material', 'qaǵaz', 'karton'],
            zh: ['材料', '纸板', '厚度'],
            tr: ['malzeme', 'karton', 'kagit'],
            tg: ['мавод', 'коғаз', 'картон', 'ғафсӣ'],
            kk: ['материал', 'қағаз', 'картон', 'қалыңдық'],
            tk: ['material', 'kagyz', 'karton', 'galyňlyk'],
            fa: ['مواد', 'کاغذ', 'مقوا', 'ضخامت'],
        },
        responses: {
            uz: "3 qavatli (E/B flute) va 5 qavatli (mustahkam) gofrokartonlarimiz mavjud. Ekologik toza va qayta ishlanadigan materiallar.",
            ru: "Используем 3-слойный (E/B flute) и 5-слойный гофрокартон. Экологичные, перерабатываемые материалы.",
            en: "We use sustainable 3-ply and 5-ply corrugated cardboard. Eco-friendly alternative to plastic.",
            qr: "3 hám 5 qabatlı ekologiyalıq taza karton.",
            zh: "我们使用3层和5层环保瓦楞纸板。",
            tr: "3 ve 5 katlı çevre dostu oluklu mukavva.",
            tg: "Картони 3-қабата (E/B flute) ва 5-қабатаи мустаҳкам мавҷуд аст.",
            kk: "3 қабатты (E/B flute) және 5 қабатты гофрокартон қолданамыз.",
            tk: "3 gatlak (E/B flute) we 5 gatlak gofrokartonymyz bar.",
            fa: "ما مقوای موج‌دار ۳ لایه و ۵ لایه استفاده می‌کنیم.",
        }
    },
    {
        id: 'printing',
        keywords: {
            uz: ['pechat', 'bosma', 'logo', 'rangli', 'print'],
            ru: ['печать', 'логотип', 'цвет', 'принт', 'нанесение'],
            en: ['printing', 'logo', 'color', 'print', 'brand'],
            qr: ['pechat', 'logo'],
            zh: ['印刷', '商标'],
            tr: ['baski', 'logo'],
            tg: ['чопкунӣ', 'лого', 'ранг'],
            kk: ['баспа', 'лого', 'түс'],
            tk: ['çap', 'logo', 'reňk'],
            fa: ['چاپ', 'لوگو', 'رنگ'],
        },
        responses: {
            uz: "Bizda 3 xil bosma usuli bor: 1) Flekso (arzon), 2) Ofset (premium), 3) Raqamli (tezkor). Sizga qaysi biri qiziq?",
            ru: "У нас 3 типа печати: 1) Флексо (дешевле), 2) Офсет (премиум), 3) Цифровая (быстро).",
            en: "We offer 3 printing types: 1) Flexo (cost-effective), 2) Offset (premium), 3) Digital (fast).",
            qr: "Bizde 3 turli pechat bar: Flekso, Ofset hám Raqamlı.",
            zh: "我们提供3种印刷类型：1）柔印，2）胶印，3）数码。",
            tr: "3 çeşit baskı sunuyoruz: 1) Flekso, 2) Ofset, 3) Dijital.",
            tg: "Мо 3 навъи чопкунӣ дорем: 1) Флексо (арзон), 2) Офсет (аъло), 3) Рақамӣ (тез).",
            kk: "Бізде 3 түрлі баспа бар: 1) Флексо (арзан), 2) Офсет (премиум), 3) Сандық (жылдам).",
            tk: "Bizde 3 görnüşli çap bar: 1) Flekso (arzan), 2) Ofset (premium), 3) Sanly (çalt).",
            fa: "ما ۳ نوع چاپ داریم: ۱) فلکسو (ارزان)، ۲) افست (برتر)، ۳) دیجیتال (سریع).",
        }
    },
    {
        id: 'payment',
        keywords: {
            uz: ['to\'lov', 'pul o\'tkazish', 'payme', 'click', 'naqd', 'karta'],
            ru: ['оплата', 'платеж', 'payme', 'click', 'карта', 'счет'],
            en: ['payment', 'pay', 'card', 'transfer', 'invoice'],
            qr: ['tólew', 'pul'],
            zh: ['付款', '支付'],
            tr: ['odeme', 'kart'],
            tg: ['пардохт', 'пул', 'кард'],
            kk: ['төлем', 'ақша', 'карта'],
            tk: ['töleg', 'pul', 'kart'],
            fa: ['پرداخت', 'پول', 'کارت'],
        },
        responses: {
            uz: "To'lov turlari: 1) Pul o'tkazish, 2) Payme/Click, 3) Naqd pul. Barcha to'lovlar rasmiy shartnoma asosida.",
            ru: "Способы оплаты: 1) Перечисление, 2) Payme/Click, 3) Наличные. Работаем официально.",
            en: "Payment methods: 1) Bank transfer, 2) Payme/Click, 3) Cash. All via official contract.",
            qr: "Tólew túrleri: Pul o'tkeriw, Payme/Click, Naqd pul.",
            zh: "付款方式：银行转账，Payme/Click，现金。",
            tr: "Ödeme yöntemleri: Havale, Payme/Click, Nakit.",
            tg: "Усулҳои пардохт: 1) Интиқоли пул, 2) Payme/Click, 3) Нақд.",
            kk: "Төлем тәсілдері: 1) Аударым, 2) Payme/Click, 3) Қолма-қол.",
            tk: "Töleg usullary: 1) Geçiriş, 2) Payme/Click, 3) Nagt.",
            fa: "روش‌های پرداخت: ۱) انتقال بانکی، ۲) Payme/Click، ۳) نقد.",
        }
    },
    {
        id: 'materials_detail',
        keywords: {
            uz: ['oq', 'jigarrang', 'kraft', 'sellyuloza', 'sifati'],
            ru: ['белый', 'бурый', 'крафт', 'целлюлоза', 'качество'],
            en: ['white', 'brown', 'kraft', 'cellulose', 'quality'],
            qr: ['aq', 'qońır', 'sapa'],
            zh: ['白色', '棕色', '质量'],
            tr: ['beyaz', 'esmer', 'kalite'],
            tg: ['сафед', 'қаҳваранг', 'крафт', 'сифат'],
            kk: ['ақ', 'қоңыр', 'крафт', 'сапа'],
            tk: ['ak', 'goňur', 'kraft', 'hil'],
            fa: ['سفید', 'قهوه‌ای', 'کرافت', 'کیفیت'],
        },
        responses: {
            uz: "Materiallar: 'Kraft' (jigarrang, mustahkam, ekologik) va 'Sellyuloza' (oppoq, yorqin pechat uchun).",
            ru: "Материалы: 'Крафт' (бурый, прочный, эко) и 'Целлюлоза' (белый, для яркой печати).",
            en: "Materials: 'Kraft' (brown, strong, eco) and 'Cellulose' (white, for premium print).",
            qr: "Materiallar: Kraft (qońır) hám Sellyuloza (aq).",
            zh: "材料：牛皮纸（棕色）和纤维素（白色）。",
            tr: "Malzemeler: Kraft (esmer) ve Selüloz (beyaz).",
            tg: "Маводҳо: 'Крафт' (қаҳваранг, мустаҳкам) ва 'Селлюлоза' (сафед, барои чопи дурахшон).",
            kk: "Материалдар: 'Крафт' (қоңыр, мықты) және 'Целлюлоза' (ақ, жарқын басма үшін).",
            tk: "Materiallar: 'Kraft' (goňur, berk) we 'Selýuloza' (ak, ýarky çap üçin).",
            fa: "مواد: 'کرافت' (قهوه‌ای، محکم) و 'سلولز' (سفید، برای چاپ درخشان).",
        }
    },
    {
        id: 'dimensions',
        keywords: {
            uz: ['o\'lcham', 'razmer', 'uzunlik', 'eni', 'balandlik', 'katta', 'kichik'],
            ru: ['размер', 'габариты', 'длина', 'ширина', 'высота', 'большой', 'маленький'],
            en: ['dimension', 'size', 'length', 'width', 'height', 'big', 'small'],
            qr: ['olshem', 'uzınlıq'],
            zh: ['尺寸', '长', '宽'],
            tr: ['boyut', 'olcu'],
            tg: ['андоза', 'дарозӣ', 'паҳнӣ', 'баландӣ'],
            kk: ['өлшем', 'ұзындық', 'ені', 'биіктік'],
            tk: ['ölçeg', 'uzynlyk', 'ini', 'belentlik'],
            fa: ['اندازه', 'طول', 'عرض', 'ارتفاع'],
        },
        responses: {
            uz: "Hozirgi model: {{modelName}}. O'lchamlari: {{length}} x {{width}} x {{height}} mm.",
            ru: "Текущая модель: {{modelName}}. Размеры: {{length}} x {{width}} x {{height}} мм.",
            en: "Current model: {{modelName}}. Dimensions: {{length}} x {{width}} x {{height}} mm.",
            qr: "Házirgi model: {{modelName}}. Olshemleri: {{length}} x {{width}} x {{height}} mm.",
            zh: "当前型号：{{modelName}}。尺寸：{{length}} x {{width}} x {{height}} mm。",
            tr: "Mevcut model: {{modelName}}. Boyutlar: {{length}} x {{width}} x {{height}} mm.",
            tg: "Модели ҷорӣ: {{modelName}}. Андозаҳо: {{length}} x {{width}} x {{height}} мм.",
            kk: "Ағымдағы модель: {{modelName}}. Өлшемдері: {{length}} x {{width}} x {{height}} мм.",
            tk: "Häzirki model: {{modelName}}. Ölçegleri: {{length}} x {{width}} x {{height}} mm.",
            fa: "مدل فعلی: {{modelName}}. ابعاد: {{length}} x {{width}} x {{height}} میلی‌متر.",
        }
    },
    {
        id: 'greeting',
        keywords: {
            uz: ['salom', 'assalom', 'qalay', 'bor'],
            ru: ['привет', 'здравствуйте', 'салом', 'есть'],
            en: ['hello', 'hi', 'hey'],
            qr: ['salom', 'qalay'],
            zh: ['你好'],
            tr: ['selam', 'merhaba'],
            tg: ['салом', 'ассалому алайкум', 'чӣ хел'],
            kk: ['сәлем', 'сәлеметсіз бе', 'қалайсыз'],
            tk: ['salam', 'merhaba', 'nähili'],
            fa: ['سلام', 'درود', 'خوش آمدید'],
        },
        responses: {
            uz: "Assalomu alaykum! Men Pack24 AI - qadoqlash bo'yicha bosh maslahatchiman. Sizga qanday yordam bera olaman?",
            ru: "Здравствуйте! Я главный AI-консультант Pack24. Готов помочь с упаковкой.",
            en: "Hello! I am the Lead AI Consultant for Pack24. How can I assist you?",
            qr: "Assalawma áleykum! Pack24 AI sizge xızmet kórsetiwge tayın.",
            zh: "你好！我是Pack24的首席AI顾问。",
            tr: "Merhaba! Pack24 Baş AI Danışmanınız hizmetinizde.",
            tg: "Ассалому алайкум! Ман Pack24 AI — маслаҳатчии асосӣ ҳастам. Чӣ гуна кӯмак карда метавонам?",
            kk: "Сәлеметсіз бе! Мен Pack24 AI — бас кеңесшімін. Қалай көмектесе аламын?",
            tk: "Salam! Men Pack24 AI — baş maslahatçy. Size nähili kömek edip bilerin?",
            fa: "سلام! من Pack24 AI هستم — مشاور اصلی بسته‌بندی. چطور می‌توانم کمک کنم؟",
        }
    }
];

