// ─── AI Conversation Prompts & Fallback ──────────────────────────────────────
import type { Language } from '../translations';

export const FALLBACK_RESPONSES: Partial<Record<Language, string>> = {
    uz: "Uzr, savolingizni tushunmadim. Iltimos, 'narx', 'yetkazib berish' haqida so'rang.",
    ru: "Извините, я не понял вопрос. Спросите про 'цену' или 'доставку'.",
    en: "Sorry, I didn't understand. Please ask about 'price' or 'delivery'.",
    qr: "Keshire siz, tusinbedim.",
    zh: "抱歉，我不明白。请询问价格或配送。",
    tr: "Üzgünüm, anlamadım.",
    tg: "Бубахшед, саволатонро нафаҳмидам.",
    kk: "Кешіріңіз, сұрағыңызды түсінбедім.",
    tk: "Bagyşlaň, soragyňyzy düşünmedim.",
    fa: "ببخشید، سوالتان را نفهمیدم.",
};

export const CONVERSATION_PROMPTS = {
    intro: {
        uz: "Assalomu Alaykum! Men Pack24 AI maslahatchisiman. Nima haqida ma'lumot olmoqchisiz?",
        ru: "Здравствуйте! Я AI-консультант Pack24. О чем вы хотели бы узнать?",
        en: "Hello! I am Pack24 AI Consultant. What would you like to know about?",
        qr: "Assalawma áleykum! Men Pack24 AI másláhátshisimen.",
        zh: "你好！我是Pack24 AI顾问。你想了解什么？",
        tr: "Merhaba! Ben Pack24 AI Danışmanıyım.",
        tg: "Ассалому алайкум! Ман маслаҳатчии Pack24 AI ҳастам.",
        kk: "Сәлеметсіз бе! Мен Pack24 AI кеңесшісімін.",
        tk: "Salam! Men Pack24 AI maslahatçy.",
        fa: "سلام! من مشاور Pack24 AI هستم.",
    },
    intent_confirm: {
        uz: "Tushunarli. Sizga {{modelName}} kerak ekan. Hozir {{quantity}} dona tanlangan.",
        ru: "Понятно. Вам нужна {{modelName}}. Сейчас выбрано {{quantity}} шт.",
        en: "Understood. You need {{modelName}}. Currently {{quantity}} units selected.",
        qr: "Tusinikli. Sizge {{modelName}} kerek eken. Házir {{quantity}} dana saylandı.",
        zh: "明白。你需要 {{modelName}}。目前选择了 {{quantity}} 个。",
        tr: "Anlaşıldı. {{modelName}} ihtiyacınız var. Şu anda {{quantity}} adet seçili.",
        tg: "Фаҳмидам. Ба шумо {{modelName}} лозим аст. Ҳоло {{quantity}} дона интихоб шудааст.",
        kk: "Түсінікті. Сізге {{modelName}} керек. Қазір {{quantity}} дана таңдалған.",
        tk: "Düşündim. Siziň {{modelName}} gerek. Häzir {{quantity}} sany saýlandy.",
        fa: "فهمیدم. شما به {{modelName}} نیاز دارید. اکنون {{quantity}} عدد انتخاب شده.",
    },
    box_qty_ask: {
        uz: "Yaxshi. Pechat masalasi: Ofset (premium) yoki Flekso (oddiy) bosma kerakmi?",
        ru: "Хорошо. Насчет печати: Офсет (премиум) или Флексо (простая)?",
        en: "Great. Regarding printing: Do you need Offset (premium) or Flexo (simple)?",
        qr: "Jaqsı. Pechat máselesi: Ofset yamasa Flekso?",
        zh: "好的。关于印刷：胶印（高级）还是柔印（简单）？",
        tr: "Harika. Baskı hakkında: Ofset (premium) mi yoksa Flekso (basit) mu?",
        tg: "Хуб. Дар бораи чопкунӣ: Офсет (аъло) ё Флексо (оддӣ)?",
        kk: "Жақсы. Баспа туралы: Офсет (премиум) немесе Флексо (қарапайым)?",
        tk: "Gowy. Çap barada: Ofset (premium) ýa-da Flekso (ýönekeý)?",
        fa: "عالی. درباره چاپ: افست (برتر) یا فلکسو (ساده)؟",
    },
    print_type_explain: {
        uz: "Flekso - arzon va tez. Ofset - qimmatroq, lekin fotosurat sifatida.",
        ru: "Флексо - дешевле и быстрее. Офсет - дороже, но фотореалистичное качество.",
        en: "Flexo is cheaper/faster. Offset is premium photo-quality.",
        qr: "Flekso - arzan hám tez. Ofset - qımbatlaw, biraq sapalı.",
        zh: "柔印更便宜/更快。胶印是照片级质量。",
        tr: "Flekso daha ucuz/hızlı. Ofset premium fotoğraf kalitesinde.",
        tg: "Флексо - арзон ва тез. Офсет - гаронтар, вале аъло сифат.",
        kk: "Флексо - арзан және жылдам. Офсет - қымбатырақ, бірақ сапалы.",
        tk: "Flekso - arzan we çalt. Ofset - gymmatrak, ýöne ýokary hilli.",
        fa: "فلکسو ارزان‌تر و سریع‌تر. افست کیفیت عکاسی دارد.",
    },
    delivery_ask: {
        uz: "Yetkazib berish xizmati kerakmi?",
        ru: "Нужна ли доставка?",
        en: "Do you need delivery service?",
        qr: "Jetkiziw xızmeti kerekpe?",
        zh: "你需要送货服务吗？",
        tr: "Teslimat hizmetine ihtiyacınız var mı?",
        tg: "Оё хизмати таҳвил лозим аст?",
        kk: "Жеткізу қызметі керек пе?",
        tk: "Eltip bermek hyzmatyna zerurlyk barmy?",
        fa: "آیا به خدمات تحویل نیاز دارید؟",
    },
    address_ask: {
        uz: "Manzilingizni yozib yuboring (Tuman, ko'cha, mo'ljal):",
        ru: "Пожалуйста, напишите ваш адрес (Район, улица, ориентир):",
        en: "Please write your address (District, street, landmark):",
        qr: "Mánzilińizdi jazıp jiberiń:",
        zh: "请写下您的地址：",
        tr: "Lütfen adresinizi yazın:",
        tg: "Лутфан суроғаи худро нависед:",
        kk: "Мекенжайыңызды жазыңыз:",
        tk: "Adresinizi ýazyň:",
        fa: "لطفاً آدرس خود را بنویسید:",
    },
    phone_ask_pickup: {
        uz: "Olib ketish (samovivoz). Telefon raqamingizni qoldiring:",
        ru: "Самовывоз. Оставьте номер телефона:",
        en: "Pickup. Please leave your phone number:",
        qr: "Alıp ketiw. Telefon nomerińizdi qaldırıń:",
        zh: "自提。请留下您的联系电话：",
        tr: "Gelip alma. Telefon numaranızı bırakın:",
        tg: "Бурдани мол. Рақами телефонро гузоред:",
        kk: "Өзі алып кету. Телефон нөміріңізді қалдырыңыз:",
        tk: "Alyp gitmek. Telefon belgiňizi galdyryň:",
        fa: "وصول شخصی. شماره تلفن خود را بگذارید:",
    },
    phone_ask_address: {
        uz: "Manzil qabul qilindi. Telefon raqamingizni qoldiring:",
        ru: "Адрес принят. Оставьте номер телефона:",
        en: "Address received. Please leave your phone number:",
        qr: "Mánzil qabıllandı. Telefon nomerińizdi qaldırıń:",
        zh: "地址已收到。请留下联系电话：",
        tr: "Adres alındı. Telefon numaranızı bırakın:",
        tg: "Суроға қабул шуд. Рақами телефон гузоред:",
        kk: "Мекенжай қабылданды. Телефон нөміріңізді қалдырыңыз:",
        tk: "Adres alyndy. Telefon belgiňizi galdyryň:",
        fa: "آدرس دریافت شد. شماره تلفن بگذارید:",
    },
    payment_ask: {
        uz: "To'lovni qaysi usulda amalga oshirasiz? (Naqd / Pul o'tkazish / Click, Payme)",
        ru: "Как будете платить? (Наличные / Перечисление / Click, Payme)",
        en: "How will you pay? (Cash / Transfer / Click, Payme)",
        qr: "Tólewdi qalay ámelge asırasız?",
        zh: "您将如何支付？（现金/转账/Click, Payme）",
        tr: "Nasıl ödeme yapacaksınız? (Nakit / Havale / Click, Payme)",
        tg: "Чӣ тавр пардохт хоҳед кард? (Нақд / Интиқол / Click, Payme)",
        kk: "Қалай төлейсіз? (Қолма-қол / Аударым / Click, Payme)",
        tk: "Nähili töleg etjeksiňiz? (Nagt / Geçiriş / Click, Payme)",
        fa: "چطور پرداخت می‌کنید؟ (نقد / انتقال / Click, Payme)",
    },
    deadline_ask: {
        uz: "Buyurtma qachonga tayyor bo'lishi kerak?",
        ru: "Когда заказ должен быть готов?",
        en: "When do you need the order ready?",
        qr: "Buyırtpa qashan tayın bolıwı kerek?",
        zh: "订单什么时候需要准备好？",
        tr: "Siparişin ne zaman hazır olması gerekiyor?",
        tg: "Фармоиш кай вақт омода бояд бошад?",
        kk: "Тапсырыс қашан дайын болуы керек?",
        tk: "Sargyt haçan taýyn bolmaly?",
        fa: "سفارش کی باید آماده باشد؟",
    },
    report_title: {
        uz: "✅ BUYURTMA QABUL QILINDI!",
        ru: "✅ ЗАКАЗ ПРИНЯТ!",
        en: "✅ ORDER RECEIVED!",
        qr: "✅ BUYIRTPA QABILLANDI!",
        zh: "✅ 订单已收到！",
        tr: "✅ SİPARİŞ ALINDI!",
        tg: "✅ ФАРМОИШ ҚАБУЛ ШУД!",
        kk: "✅ ТАПСЫРЫС ҚАБЫЛДАНДЫ!",
        tk: "✅ SARGYT KABUL EDILDI!",
        fa: "✅ سفارش دریافت شد!",
    },
    report_labels: {
        uz: { product: "Maxsulot", qty: "Soni", material: "Material", print: "Pechat", delivery: "Yetkazib berish", phone: "Tel", payment: "To'lov", deadline: "Muddat", footer: "Menejerimiz tez orada siz bilan bog'lanadi!" },
        ru: { product: "Продукт", qty: "Кол-во", material: "Материал", print: "Печать", delivery: "Доставка", phone: "Тел", payment: "Оплата", deadline: "Срок", footer: "Наш менеджер скоро свяжется с вами!" },
        en: { product: "Product", qty: "Qty", material: "Material", print: "Print", delivery: "Delivery", phone: "Phone", payment: "Payment", deadline: "Deadline", footer: "Our manager will contact you soon!" },
        qr: { product: "Onim", qty: "Sanı", material: "Material", print: "Pechat", delivery: "Jetkiziw", phone: "Tel", payment: "Tólew", deadline: "Múddet", footer: "Menejerimiz tez arada xabarlasadı!" },
        zh: { product: "产品", qty: "数量", material: "材料", print: "印刷", delivery: "送货", phone: "电话", payment: "付款", deadline: "期限", footer: "我们的经理会尽快联系您！" },
        tr: { product: "Ürün", qty: "Adet", material: "Malzeme", print: "Baskı", delivery: "Teslimat", phone: "Tel", payment: "Ödeme", deadline: "Süre", footer: "Yöneticimiz yakında sizinle iletişime geçecek!" },
        tg: { product: "Маҳсулот", qty: "Миқдор", material: "Мавод", print: "Чоп", delivery: "Таҳвил", phone: "Тел", payment: "Пардохт", deadline: "Мӯҳлат", footer: "Менеҷери мо ба зудӣ бо шумо тамос хоҳад гирифт!" },
        kk: { product: "Өнім", qty: "Саны", material: "Материал", print: "Баспа", delivery: "Жеткізу", phone: "Тел", payment: "Төлем", deadline: "Мерзім", footer: "Біздің менеджер жақында сізбен хабарласады!" },
        tk: { product: "Önüm", qty: "Sany", material: "Material", print: "Çap", delivery: "Eltip bermek", phone: "Tel", payment: "Töleg", deadline: "Möhlet", footer: "Menejerimiz tiz wagtda siz bilen habarlaşar!" },
        fa: { product: "محصول", qty: "تعداد", material: "مواد", print: "چاپ", delivery: "تحویل", phone: "تلفن", payment: "پرداخت", deadline: "مهلت", footer: "مدیر ما به زودی با شما تماس خواهد گرفت!" },
    },
    finished_ask: {
        uz: "Yana qanday yordam bera olaman?",
        ru: "Чем еще могу помочь?",
        en: "How else can I help?",
        qr: "Jáne qanday járdem bere alaman?",
        zh: "我还能帮您什么吗？",
        tr: "Başka nasıl yardımcı olabilirim?",
        tg: "Боз чӣ гуна кӯмак карда метавонам?",
        kk: "Тағы қалай көмектесе аламын?",
        tk: "Ýene nähili kömek edip bilerin?",
        fa: "چه کمک دیگری می‌توانم بکنم؟",
    }
};

